# Generated by Django 5.1.7 on 2025-03-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='subject',
            field=models.CharField(default=2.5, max_length=200),
            preserve_default=False,
        ),
    ]
