# Generated by Django 5.1.7 on 2025-03-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactus_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinquiry',
            options={},
        ),
    ]
